[package]
name = "md-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
rust_decimal.workspace = true
serde.workspace = true
thiserror.workspace = true
toml.workspace = true

